#!/usr/bin/env node
// Checks the built site in dist/ for broken internal links and docs pages
// missing from the sidebar. `--external` also probes external links and
// reports (never fails on) the results.
//
// Usage: node scripts/check-links.mjs [--external] [distDir]

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';

// Docs pages that are intentionally reached from a hub page instead of the
// sidebar. Each page under `prefix` must be linked from `hub`. Add an entry
// here when a new family of detail pages gets its own index page.
export const HUB_LINKED_DOCS = [
  // Generated by cli/scripts/sync-fedramp.ts.
  { prefix: '/docs/fedramp/ksi/', hub: '/docs/fedramp/ksis/' },
  { prefix: '/docs/fedramp/processes/', hub: '/docs/fedramp/processes/' },
];

const LINK_ATTRS = new Set(['href', 'src', 'srcset', 'poster']);
// RFC 3986 scheme. Only http(s) and protocol-relative URLs are probed by
// --external; mailto:, sms:, data:, and other schemes are not site paths.
const URI_SCHEME = /^([A-Za-z][A-Za-z0-9+.-]*):/;
const WEB_SCHEMES = new Set(['http', 'https']);
// Only these count as navigation for the sidebar and hub backlink rules.
const NAV_TAGS = new Set(['a', 'area']);
const ORIGIN = 'https://site.invalid';
// Comments, plus the bodies of elements whose contents are text rather than
// markup. The opening tag is kept so attributes like `<script src>` are checked.
const NON_MARKUP = /<!--[\s\S]*?-->|<(script|style|textarea|title)\b((?:"[^"]*"|'[^']*'|[^"'>])*)>[\s\S]*?<\/\1\s*>/gi;

const EXTERNAL_TIMEOUT_MS = 10000;
const EXTERNAL_CONCURRENCY = 8;
// Bot walls and rate limits, not proof that a page is gone.
const BLOCKED_STATUSES = new Set([401, 403, 429, 999]);

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

function decodeEntities(value) {
  return value
    .replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(Number(dec)))
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');
}

export function parseTags(html) {
  const markup = html.replace(NON_MARKUP, (_, name, attrs) => (name ? `<${name}${attrs}>` : ''));
  const tagPattern = /<([a-zA-Z][\w-]*)((?:\s+[^\s"'>/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s"'=<>`]+))?)*)\s*\/?>/g;
  const attrPattern = /([^\s"'>/=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g;
  const tags = [];
  for (const [, name, rawAttrs] of markup.matchAll(tagPattern)) {
    const attrs = {};
    for (const [, key, dq, sq, bare] of rawAttrs.matchAll(attrPattern)) {
      attrs[key.toLowerCase()] = decodeEntities(dq ?? sq ?? bare ?? '');
    }
    tags.push({ name: name.toLowerCase(), attrs });
  }
  return tags;
}

// Candidate URLs from a srcset, following the HTML "parse a srcset attribute"
// steps: a URL is a run of non-whitespace (so it may contain commas, as data
// URLs do), and its descriptors run to the next comma outside parentheses.
export function parseSrcset(value) {
  const urls = [];
  let i = 0;
  while (i < value.length) {
    while (i < value.length && /[\s,]/.test(value[i])) i += 1;
    let end = i;
    while (end < value.length && !/\s/.test(value[end])) end += 1;
    let url = value.slice(i, end);
    i = end;
    if (url.endsWith(',')) {
      url = url.replace(/,+$/, '');
    } else {
      let depth = 0;
      for (; i < value.length && (value[i] !== ',' || depth > 0); i += 1) {
        if (value[i] === '(') depth += 1;
        if (value[i] === ')') depth = Math.max(0, depth - 1);
      }
    }
    if (url) urls.push(url);
  }
  return urls;
}

function linksFrom(tags) {
  const links = [];
  for (const { name, attrs } of tags) {
    for (const [key, value] of Object.entries(attrs)) {
      if (!LINK_ATTRS.has(key)) continue;
      const refs = key === 'srcset' ? parseSrcset(value) : [value.trim()];
      for (const ref of refs) {
        if (ref) links.push({ ref, rel: attrs.rel ?? '', nav: key === 'href' && NAV_TAGS.has(name) });
      }
    }
  }
  return links;
}

// Mirrors Workers static assets `html_handling: auto-trailing-slash`: /file,
// /file.html, /file/, /file/index, and /file/index.html all reach file.html,
// and the same spellings of /folder reach folder/index.html. When both
// x.html and x/index.html exist, /x prefers x.html while /x/ and /x/index
// prefer x/index.html. Anything else gets the `not_found_handling: 404-page`
// response, so a miss is a broken link.
export function resolveTarget(pathname, files) {
  if (files.has(pathname)) return pathname;
  const base = pathname.replace(/(\/index\.html|\/index|\.html|\/)$/, '');
  const candidates = [`${base}.html`, `${base}/index.html`];
  if (/(\/|\/index(\.html)?)$/.test(pathname)) candidates.reverse();
  return candidates.find((candidate) => files.has(candidate));
}

function baseUrl(file) {
  return file.endsWith('/index.html') ? file.slice(0, -'index.html'.length) : file;
}

export function checkSite({ distDir = 'dist', hubs = HUB_LINKED_DOCS } = {}) {
  const allFiles = walk(distDir);
  const toKey = (file) => '/' + relative(distDir, file).split(sep).join('/');
  const files = new Set(allFiles.map(toKey));
  const pages = new Map();
  for (const file of allFiles.filter((path) => path.endsWith('.html'))) {
    const tags = parseTags(readFileSync(file, 'utf8'));
    const ids = new Set();
    for (const { name, attrs } of tags) {
      if (attrs.id) ids.add(attrs.id);
      if (name === 'a' && attrs.name) ids.add(attrs.name);
    }
    pages.set(toKey(file), { file: relative('.', file), tags, ids, links: linksFrom(tags) });
  }

  const problems = [];
  const external = new Map();
  const inbound = new Map();
  let internalLinks = 0;

  for (const [key, page] of pages) {
    for (const { ref, rel, nav } of page.links) {
      const scheme = ref.match(URI_SCHEME)?.[1].toLowerCase();
      if (scheme?.length === 1) {
        problems.push(`${page.file}: ${ref} (looks like a local drive path)`);
        continue;
      }
      if (scheme && !WEB_SCHEMES.has(scheme)) continue;
      if (scheme || ref.startsWith('//')) {
        if (/\b(preconnect|dns-prefetch)\b/.test(rel)) continue;
        const target = new URL(ref, ORIGIN);
        target.hash = '';
        if (!external.has(target.href)) external.set(target.href, new Set());
        external.get(target.href).add(page.file);
        continue;
      }
      internalLinks += 1;
      const target = new URL(ref, ORIGIN + baseUrl(key));
      let pathname;
      let fragment;
      try {
        pathname = decodeURIComponent(target.pathname);
        fragment = decodeURIComponent(target.hash.slice(1));
      } catch {
        problems.push(`${page.file}: ${ref} (malformed percent-encoding)`);
        continue;
      }
      const resolved = resolveTarget(pathname, files);
      if (!resolved) {
        problems.push(`${page.file}: ${ref} (no built file)`);
        continue;
      }
      if (!pages.has(resolved)) continue;
      if (nav && resolved !== key) {
        if (!inbound.has(resolved)) inbound.set(resolved, new Set());
        inbound.get(resolved).add(key);
      }
      if (fragment && fragment !== 'top' && !pages.get(resolved).ids.has(fragment)) {
        problems.push(`${page.file}: ${ref} (no id="${fragment}" on ${resolved})`);
      }
    }
  }

  const sidebar = new Set();
  const sidebarNav = readFileSync(join(distDir, 'docs', 'index.html'), 'utf8')
    .match(/<nav class="docs-sidebar-nav"[\s\S]*?<\/nav>/)?.[0];
  for (const { ref } of linksFrom(parseTags(sidebarNav ?? '')).filter(({ nav }) => nav)) {
    sidebar.add(resolveTarget(new URL(ref, ORIGIN).pathname, files));
  }
  if (sidebar.size === 0) problems.push(`${join(distDir, 'docs', 'index.html')}: no docs sidebar links found`);

  for (const key of pages.keys()) {
    if (!key.startsWith('/docs/') || sidebar.has(key)) continue;
    const rule = hubs.find(({ prefix }) => key.startsWith(prefix));
    const hub = rule && resolveTarget(rule.hub, files);
    if (!rule) {
      problems.push(`${pages.get(key).file}: not in the docs sidebar (src/lib/docs.ts docsSections)`);
    } else if (!inbound.get(key)?.has(hub)) {
      problems.push(`${pages.get(key).file}: not linked from its hub page ${rule.hub}`);
    }
  }

  return { problems, external, stats: { pages: pages.size, internalLinks, sidebar: sidebar.size } };
}

async function probe(url) {
  for (const method of ['HEAD', 'GET']) {
    try {
      const res = await fetch(url, {
        method,
        redirect: 'follow',
        signal: AbortSignal.timeout(EXTERNAL_TIMEOUT_MS),
        headers: { 'user-agent': 'grclanker-link-check (+https://grclanker.com)' },
      });
      await res.body?.cancel();
      if (method === 'HEAD' && res.status >= 400) continue;
      return { status: res.status, finalUrl: res.url };
    } catch (error) {
      if (method === 'GET') return { error: error.cause?.code ?? error.name };
    }
  }
}

async function reportExternal(urls) {
  const queue = [...urls.keys()].sort();
  const results = new Map();
  const worker = async () => {
    while (queue.length > 0) {
      const url = queue.shift();
      results.set(url, await probe(url));
    }
  };
  await Promise.all(Array.from({ length: EXTERNAL_CONCURRENCY }, worker));

  const groups = { broken: [], blocked: [], redirected: [], ok: [] };
  for (const [url, result] of [...results].sort(([a], [b]) => a.localeCompare(b))) {
    const where = [...urls.get(url)].sort().join(', ');
    if (BLOCKED_STATUSES.has(result.status)) {
      groups.blocked.push(`${result.status} ${url}`);
    } else if (result.error || result.status >= 400) {
      groups.broken.push(`${result.error ?? result.status} ${url}\n      on ${where}`);
    } else if (result.finalUrl !== url) {
      groups.redirected.push(`${result.status} ${url} -> ${result.finalUrl}`);
    } else {
      groups.ok.push(url);
    }
  }
  console.log(
    `\ncheck-links --external: ${results.size} URLs, ${groups.ok.length} ok, ` +
    `${groups.redirected.length} redirected, ${groups.blocked.length} blocked or rate-limited, ` +
    `${groups.broken.length} broken or unreachable (reported, not failed)`,
  );
  for (const title of ['broken', 'blocked', 'redirected']) {
    if (groups[title].length === 0) continue;
    console.log(`\n  ${title}:`);
    for (const line of groups[title]) console.log(`    ${line}`);
  }
}

async function main() {
  const args = process.argv.slice(2);
  const distDir = args.find((arg) => !arg.startsWith('--')) ?? 'dist';
  if (!existsSync(join(distDir, 'docs', 'index.html'))) {
    console.error(`check-links: ${distDir}/docs/index.html not found; run \`npm run build\` first.`);
    process.exit(1);
  }

  const started = Date.now();
  const { problems, external, stats } = checkSite({ distDir });
  console.log(
    `check-links: ${stats.pages} pages, ${stats.internalLinks} internal links, ` +
    `${stats.sidebar} sidebar entries, ${external.size} unique external URLs ` +
    `(${Date.now() - started}ms)`,
  );

  if (args.includes('--external')) await reportExternal(external);

  if (problems.length > 0) {
    console.error(`\ncheck-links: ${problems.length} problem(s):`);
    for (const problem of problems) console.error(`  ${problem}`);
    process.exit(1);
  }
  console.log('check-links: no broken internal links or orphaned docs pages');
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  await main();
}
