import { buildBatchIntegrationSpec, type BatchCheckDefinition } from "./batch-spec-builder.js";

const checkRows = [
  ["SLACK-ID-01", 2, "MFA enrollment", "critical", "slack_assess_identity"],
  ["SLACK-ID-02", 15, "Guest account inventory", "medium", "slack_assess_identity"],
  ["SLACK-ID-03", 22, "SCIM provisioning coverage", "high", "slack_assess_identity"],
  ["SLACK-ID-04", 23, "User lifecycle alignment", "high", "slack_assess_identity"],
  ["SLACK-ID-05", 23, "Deactivated user visibility", "info", "slack_assess_identity"],
  ["SLACK-ADMIN-01", 14, "Workspace admin inventory", "high", "slack_assess_admin_access"],
  ["SLACK-ADMIN-02", 1, "SSO enforcement", "critical", "slack_assess_admin_access"],
  ["SLACK-ADMIN-03", 3, "Session duration limits", "high", "slack_assess_admin_access"],
  ["SLACK-ADMIN-04", 4, "Session idle timeout", "medium", "slack_assess_admin_access"],
  ["SLACK-ADMIN-05", 17, "Workspace discoverability", "medium", "slack_assess_admin_access"],
  ["SLACK-ADMIN-06", 5, "Mobile session controls", "medium", "slack_assess_admin_access"],
  ["SLACK-ADMIN-07", 16, "Email domain restrictions", "high", "slack_assess_admin_access"],
  ["SLACK-ADMIN-08", 19, "Custom emoji governance", "low", "slack_assess_admin_access"],
  ["SLACK-ADMIN-09", 24, "Workspace analytics access", "medium", "slack_assess_admin_access"],
  ["SLACK-APP-01", 9, "Approved app inventory", "high", "slack_assess_integrations"],
  ["SLACK-APP-02", 9, "Restricted app policy", "medium", "slack_assess_integrations"],
  ["SLACK-APP-03", 10, "Custom and sensitive-scope apps", "medium", "slack_assess_integrations"],
  ["SLACK-APP-04", 8, "Information barriers", "high", "slack_assess_integrations"],
  ["SLACK-APP-05", 11, "DLP and Discovery evidence", "medium", "slack_assess_integrations"],
  ["SLACK-APP-06", 6, "File upload restrictions", "medium", "slack_assess_integrations"],
  ["SLACK-APP-07", 25, "Token rotation and revocation", "medium", "slack_assess_integrations"],
  ["SLACK-CHAN-01", 7, "Slack Connect exposure", "high", "slack_assess_channel_governance"],
  ["SLACK-CHAN-02", 18, "Channel posting restrictions", "medium", "slack_assess_channel_governance"],
  ["SLACK-CHAN-03", 12, "Channel retention overrides", "medium", "slack_assess_channel_governance"],
  ["SLACK-CHAN-04", 20, "External email ingestion", "medium", "slack_assess_channel_governance"],
  ["SLACK-CHAN-05", 21, "Link previews and URL unfurling", "medium", "slack_assess_channel_governance"],
  ["SLACK-MON-01", 13, "Audit Logs API access", "critical", "slack_assess_monitoring"],
  ["SLACK-MON-02", 13, "Audit log recency", "high", "slack_assess_monitoring"],
  ["SLACK-MON-03", 13, "Security event visibility", "medium", "slack_assess_monitoring"],
  ["SLACK-MON-04", 13, "Audit schema visibility", "low", "slack_assess_monitoring"],
  ["SLACK-MON-05", 7, "External sharing monitoring", "medium", "slack_assess_monitoring"],
  ["SLACK-MON-06", 13, "SIEM streaming evidence", "medium", "slack_assess_monitoring"],
] as const;

const checks: BatchCheckDefinition[] = checkRows.map(([id, control, title, severity, owner]) => ({
  id,
  control,
  title,
  severity,
  owner,
}));
const idsFor = (owner: string): string[] => checks.filter((check) => check.owner === owner).map((check) => check.id);

export const SLACK_RUNTIME_BEHAVIOR = [
  "Eight controls remain manual because the public read APIs do not expose a decisive setting; the runtime names the exact Admin Console or SIEM evidence instead of calling write endpoints.",
  "Cross-inventory findings require every dependent workspace, admin, channel, SCIM, or audit inventory to be complete before pass; partial secondary reads demote the dependent result.",
  "SCIM, Web API, Admin API, and Audit Logs pagination use different cursor locations and preserve stalled cursors, page caps, item caps, and unknown totals as incomplete evidence.",
] as const;

export const SLACK_SPEC = buildBatchIntegrationSpec({
  slug: "slack-sec-inspector",
  displayName: "Slack Security Inspector",
  vendor: "Slack",
  category: "collaboration",
  summary: "Portable contract for the shipped Slack Enterprise Grid identity, administration, app, channel, and monitoring assessments.",
  sourceModule: "cli/extensions/grc-tools/slack.ts",
  baseServices: ["Slack Web API", "Slack Admin API", "Slack SCIM API", "Slack Audit Logs API"],
  authentication: {
    modes: ["User OAuth token", "Bot OAuth token", "SCIM bearer token"],
    precedence: ["Explicit tool arguments", "Explicit config file", "SLACK_* environment variables"],
    environment: ["SLACK_USER_TOKEN", "SLACK_BOT_TOKEN", "SLACK_SCIM_TOKEN", "SLACK_ORG_ID", "SLACK_CONFIG_FILE"],
    configLocations: ["~/.config/grclanker/slack.json"],
    variants: ["Enterprise Grid org token plus optional bot and SCIM credentials"],
    configFields: ["token", "botToken", "scimToken", "orgId", "webApiBaseUrl", "scimBaseUrl", "auditBaseUrl"],
  },
  permissions: ["Slack Enterprise Grid org-admin OAuth scopes", "SCIM API entitlement and token", "Audit Logs API entitlement and scope", "Discovery and DLP plan features where applicable"],
  surfaces: [
    { id: "users", path: "/api/users.list", service: "Slack Web API", documentationUrl: "https://api.slack.com/methods/users.list", fields: ["id", "deleted", "is_admin", "is_owner", "is_restricted", "has_2fa", "has_sso"] },
    { id: "admin-users", method: "POST", path: "/api/admin.users.list", service: "Slack Admin API", documentationUrl: "https://api.slack.com/methods/admin.users.list", fields: ["id", "team_id", "email", "is_admin", "is_owner"] },
    { id: "admin-apps", path: "/api/admin.apps.approved.list", service: "Slack Admin API", documentationUrl: "https://api.slack.com/methods/admin.apps.approved.list", fields: ["app_id", "name", "scopes", "is_internal"] },
    { id: "scim-users", path: "/scim/v1/Users", service: "Slack SCIM API", documentationUrl: "https://docs.slack.dev/admins/scim-api/", fields: ["id", "userName", "active", "groups"] },
    { id: "audit-logs", path: "/audit/v1/logs", service: "Slack Audit Logs API", documentationUrl: "https://docs.slack.dev/admins/audit-logs-api/", fields: ["id", "date_create", "action", "actor", "entity", "context"] },
  ],
  checks,
  tools: {
    slack_check_access: [],
    slack_assess_identity: idsFor("slack_assess_identity"),
    slack_assess_admin_access: idsFor("slack_assess_admin_access"),
    slack_assess_integrations: idsFor("slack_assess_integrations"),
    slack_assess_channel_governance: idsFor("slack_assess_channel_governance"),
    slack_assess_monitoring: idsFor("slack_assess_monitoring"),
    slack_export_audit_bundle: checks.map((check) => check.id),
  },
  pagination: {
    cursorFields: ["response_metadata.next_cursor", "next_cursor", "startIndex", "totalResults"],
    pageSize: null,
    itemCap: null,
    pageCap: 50,
    totalSemantics: "SCIM totals are authoritative; Slack cursor APIs prove completion only with an empty next cursor.",
    stopConditions: ["Empty next cursor or SCIM total reached", "Configured item cap", "Page cap", "Repeated cursor", "Empty page with cursor", "Unknown or inconsistent SCIM total"],
  },
  rateLimit: {
    documentedLimit: "Method-specific Slack rate tiers",
    retryHeaders: ["Retry-After"],
    retryableStatuses: [429, 500, 502, 503, 504],
    backoffPolicy: "Honor Retry-After up to the runtime bound and retry 429 responses twice; exhausted reads stay explicit.",
  },
  runtimeBehavior: SLACK_RUNTIME_BEHAVIOR,
  knownGaps: ["Discovery DLP details, guest expiry, several workspace restrictions, and standalone reporters remain unavailable."],
  sensitiveFields: ["token", "scimToken", "authorization", "cookie", "webhook_url"],
  credentialFormats: ["xoxb, xoxp, xoxe, and xapp token families", "SCIM bearer tokens", "webhook path secrets"],
  outputPrefix: "slack-audit",
});
